version: '3.8'

services:
  frontend:
    build:
      context: ./NextJS/FE/package
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:8000/token
    depends_on:
      - backend

  backend:
    build:
      context: ./python
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DBHOST=db
      - SQL_USERNAME=${SQL_USERNAME}
      - SQL_PASSWORD=${SQL_PASSWORD}
      - DB_NAME=${DB_NAME}
      - AzureConnectionFlag=False
    depends_on:
      - db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${SQL_USERNAME}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"

volumes:
  postgres_data:
