"""Add markdown notes and note links tables

Revision ID: 23db5c49d29d
Revises: 338d7403b4d1
Create Date: 2025-06-20 10:11:37.308950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23db5c49d29d'
down_revision: Union[str, None] = '338d7403b4d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('helloworld',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_helloworld_id'), 'helloworld', ['id'], unique=False)
    op.create_table('textbox_commit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_textbox_commit_id'), 'textbox_commit', ['id'], unique=False)
    op.create_table('textbox_draft',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_textbox_draft_id'), 'textbox_draft', ['id'], unique=False)
    op.create_table('markdown_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_markdown_notes_id'), 'markdown_notes', ['id'], unique=False)
    op.create_index(op.f('ix_markdown_notes_title'), 'markdown_notes', ['title'], unique=False)
    op.create_table('note_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_note_id', sa.Integer(), nullable=False),
    sa.Column('target_note_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_note_id'], ['markdown_notes.id'], ),
    sa.ForeignKeyConstraint(['target_note_id'], ['markdown_notes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_note_links_id'), 'note_links', ['id'], unique=False)
    op.drop_column('user', 'first_name')
    op.drop_column('user', 'last_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_name', sa.VARCHAR(), nullable=True))
    op.add_column('user', sa.Column('first_name', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_note_links_id'), table_name='note_links')
    op.drop_table('note_links')
    op.drop_index(op.f('ix_markdown_notes_title'), table_name='markdown_notes')
    op.drop_index(op.f('ix_markdown_notes_id'), table_name='markdown_notes')
    op.drop_table('markdown_notes')
    op.drop_index(op.f('ix_textbox_draft_id'), table_name='textbox_draft')
    op.drop_table('textbox_draft')
    op.drop_index(op.f('ix_textbox_commit_id'), table_name='textbox_commit')
    op.drop_table('textbox_commit')
    op.drop_index(op.f('ix_helloworld_id'), table_name='helloworld')
    op.drop_table('helloworld')
    # ### end Alembic commands ###
